### ISSUE TITLE
Donate npm module?

### ISSUE THREAD

**Issue by MKRhere** [AnyFetch/seeder.js#5]
Since it seems like `seeder` is no longer maintained, would you consider donating the npm package to me? I have a very similar project, which I'd also like to name Seeder.

It does more than inserting nested folders into a database. It uses my [JSONT](https://github.com/codefeathers/jsont) module to create dynamic seeds.

If you wish to keep the module, I totally understand :) Cheers.

**Comment by Neamar** [comment]
No issues giving the name away -- just tell me what I need to do by email at neamar@neamar.fr :)
